"""update model Chat, add model ChatMessage

Revision ID: f0702883f4b3
Revises: e3988fee3382
Create Date: 2025-03-09 15:23:13.912605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f0702883f4b3"
down_revision: Union[str, None] = "e3988fee3382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("chat_id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("text", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_chat_id"),
        "chat_messages",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_created_at"),
        "chat_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_updated_at"),
        "chat_messages",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_user_id"),
        "chat_messages",
        ["user_id"],
        unique=False,
    )
    op.drop_index("ix_chat_created_at", table_name="chat")
    op.drop_index("ix_chat_updated_at", table_name="chat")
    op.create_unique_constraint(
        "unique_chat_users", "chat", ["first_user_id", "second_user_id"]
    )
    op.drop_column("chat", "created_at")
    op.drop_column("chat", "updated_at")
    op.drop_column("chat", "text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat",
        sa.Column(
            "text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "chat",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "chat",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("unique_chat_users", "chat", type_="unique")
    op.create_index("ix_chat_updated_at", "chat", ["updated_at"], unique=False)
    op.create_index("ix_chat_created_at", "chat", ["created_at"], unique=False)
    op.drop_index(op.f("ix_chat_messages_user_id"), table_name="chat_messages")
    op.drop_index(
        op.f("ix_chat_messages_updated_at"), table_name="chat_messages"
    )
    op.drop_index(
        op.f("ix_chat_messages_created_at"), table_name="chat_messages"
    )
    op.drop_index(op.f("ix_chat_messages_chat_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    # ### end Alembic commands ###
