"""create chat model

Revision ID: e3988fee3382
Revises: 8fcd13cea0b4
Create Date: 2025-03-09 14:00:55.899362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3988fee3382"
down_revision: Union[str, None] = "08084a0b5d47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("first_user_id", sa.BIGINT(), nullable=False),
        sa.Column("second_user_id", sa.BIGINT(), nullable=False),
        sa.Column("text", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["second_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_created_at"), "chat", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_chat_first_user_id"), "chat", ["first_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_second_user_id"),
        "chat",
        ["second_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_updated_at"), "chat", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_updated_at"), table_name="chat")
    op.drop_index(op.f("ix_chat_second_user_id"), table_name="chat")
    op.drop_index(op.f("ix_chat_first_user_id"), table_name="chat")
    op.drop_index(op.f("ix_chat_created_at"), table_name="chat")
    op.drop_table("chat")
    # ### end Alembic commands ###
